#ifndef __PRINTF_CONFIG_H__
#define __PRINTF_CONFIG_H__
#define PRINTF_DISABLE_SUPPORT_FLOAT
#define PRINTF_DISABLE_SUPPORT_EXPONENTIAL
#define PRINTF_DISABLE_SUPPORT_LONG_LONG
#define PRINTF_DISABLE_SUPPORT_PTRDIFF_T
#endif /* __PRINTF_CONFIG_H__ */
